export interface ImageThumbnail {
	url: string,
	width: number,
	height: number,
}

export interface Image {
	url: string,
	width: number,
	height: number,
	thumbnails?: ImageThumbnail[],
	alternateText?: string,
}

export enum Mid_pageButton1 {
	Get_Started = "Get Started",
	Learn_More = "Learn More",
	Schedule_Appointment = "Schedule Appointment",
	Start_Print_Order = "Start Print Order",
	Contact_Us = "Contact Us",
	Request_Quote = "Request Quote",
	Reserve_Storage = "Reserve Storage",
	Download_Mailbox_Agreement = "Download Mailbox Agreement",
	Download_House_Account_Application = "Download House Account Application",
	Auction_Shipping_Quote = "Auction Shipping Quote",
}

export enum Mid_pageButton2 {
	Get_Started = "Get Started",
	Learn_More = "Learn More",
	Schedule_Appointment = "Schedule Appointment",
	Start_Print_Order = "Start Print Order",
	Contact_Us = "Contact Us",
	Request_Quote = "Request Quote",
	Reserve_Storage = "Reserve Storage",
	Download_Mailbox_Agreement = "Download Mailbox Agreement",
	Download_House_Account_Application = "Download House Account Application",
	Auction_Shipping_Quote = "Auction Shipping Quote",
}

export interface C_corporateMidPageSection {
	'mid-pageFeaturedImage'?: Image,
	sectionTitle?: string,
	subtitle?: string,
	details1?: string,
	serviceHighlights?: string[],
	details2?: string,
	boldTextAboveButtons?: string,
	smallerTextAboveButtons?: string,
	'mid-pageButton1'?: Mid_pageButton1,
	'mid-pageButton1Click-throughUrl'?: string,
	'mid-pageButton2'?: Mid_pageButton2,
	'mid-pageButton2Click-throughUrl'?: string,
}

export interface HeroImageGallery {
	image?: Image,
	description?: string,
}

export interface C_corporatePageHeaderSection {
	pageTitle?: string,
	defaultIntroduction?: string,
	heroImageGallery?: HeroImageGallery[],
	enablePageHeaderVideo?: boolean,
	enablePageHeaderVideoOnMobile?: boolean,
}

export interface ComplexImage {
	image: Image,
	details?: string,
	description?: string,
	clickthroughUrl?: string,
}

export enum C_corporateService1Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService2Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService3Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService4Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService5Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService6Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService7Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export enum C_corporateService8Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
	POSTAL_SERVICES = "Postal Services",
}

export interface C_customFAQGroup1 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export interface C_customFAQGroup2 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export interface C_customFAQGroup3 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export enum C_customFeaturedService1Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
}

export enum C_customFeaturedService2Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
}

export enum C_customFeaturedService3Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
}

export enum C_customFeaturedService4Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
}

export enum C_customFeaturedService5Link2 {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
	BUSINESS_CARDS = "Business Cards",
	BROCHURES = "Brochures",
	DIRECT_MAIL = "Direct Mail",
	POSTCARDS = "Postcards",
	BLUEPRINTS___ARCHITECTURAL_PRINTING = "Blueprints & Architectural Printing",
	PACK___SHIP_GUARANTEE = "Pack & Ship Guarantee",
	LOCKER_SERVICE = "Locker Service",
	MATTRESS_SHIPPING_QUOTE = "Mattress Shipping Quote",
}

export interface C_defaultFAQGroup1 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export interface C_defaultFAQGroup2 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export interface C_defaultFAQGroup3 {
	faqGroupTitle?: string,
	question1?: string,
	answer1?: string,
	question2?: string,
	answer2?: string,
	question3?: string,
	answer3?: string,
	question4?: string,
	answer4?: string,
	question5?: string,
	answer5?: string,
}

export enum C_featuredServiceTemplateType {
	LARGE = "Large",
	SMALL = "Small",
}

export interface ComplexVideo {
	url: string,
	video?: string,
	description?: string,
}

export interface EntityReference {
	entityId: string,
	name: string,
}

export interface C_midPageSection {
	'displayDefaultMid-pageSection'?: boolean,
	'mid-pageFeaturedImage'?: Image,
	sectionTitle?: string,
	subtitle?: string,
	details1?: string,
	serviceHighlights?: string[],
	details2?: string,
	boldTextAboveButtons?: string,
	smallerTextAboveButtons?: string,
	'mid-pageButton1'?: Mid_pageButton1,
	'mid-pageButton1Click-throughUrl'?: string,
	'mid-pageButton2'?: Mid_pageButton2,
	'mid-pageButton2Click-throughUrl'?: string,
}

export enum LinkType {
	OTHER = "Other",
	URL = "URL",
	PHONE = "Phone",
	EMAIL = "Email",
}

export interface CTA {
	label?: string,
	linkType?: LinkType,
	link?: string,
}

export interface SectionItem {
	title?: string,
	description?: any,
	image?: Image,
	cTA?: CTA,
}

export interface C_ourOffers {
	sectionTitle?: string,
	sectionItem?: SectionItem[],
}

export interface C_ourServices {
	sectionTitle?: string,
	sectionItem?: SectionItem[],
}

export enum PageHeaderButton1 {
	Get_Started = "Get Started",
	Learn_More = "Learn More",
	Schedule_Appointment = "Schedule Appointment",
	Start_Print_Order = "Start Print Order",
	Contact_Us = "Contact Us",
	Request_Quote = "Request Quote",
	Reserve_Storage = "Reserve Storage",
	Download_Mailbox_Agreement = "Download Mailbox Agreement",
	Download_House_Account_Application = "Download House Account Application",
	Auction_Shipping_Quote = "Auction Shipping Quote",
}

export enum PageHeaderButton2 {
	Get_Started = "Get Started",
	Learn_More = "Learn More",
	Schedule_Appointment = "Schedule Appointment",
	Start_Print_Order = "Start Print Order",
	Contact_Us = "Contact Us",
	Request_Quote = "Request Quote",
	Reserve_Storage = "Reserve Storage",
	Download_Mailbox_Agreement = "Download Mailbox Agreement",
	Download_House_Account_Application = "Download House Account Application",
	Auction_Shipping_Quote = "Auction Shipping Quote",
}

export interface C_pageHeaderSection {
	customIntroduction?: string,
	displayDefaultIntroduction?: boolean,
	serviceHighlights?: string[],
	boldTextAboveButtons?: string,
	smallerTextAboveButtons?: string,
	pageHeaderButton1?: PageHeaderButton1,
	'pageHeaderButton1Click-throughUrl'?: string,
	pageHeaderButton2?: PageHeaderButton2,
	'pageHeaderButton2Click-throughUrl'?: string,
	displayPageHeaderVideo?: boolean,
}

export enum C_pricingButton1 {
	START_PRINT_ORDER = "Start Print Order",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	CONTACT_US = "Contact Us",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_pricingButton2 {
	START_PRINT_ORDER = "Start Print Order",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	CONTACT_US = "Contact Us",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_pricingButton3 {
	START_PRINT_ORDER = "Start Print Order",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	CONTACT_US = "Contact Us",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export interface PricingInfo {
	title?: string,
	price?: string,
}

export interface C_pricingField1 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField10 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField11 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField12 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField2 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField3 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField4 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField5 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField6 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField7 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField8 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_pricingField9 {
	title?: string,
	description?: string,
	pricingInfo?: PricingInfo[],
}

export interface C_searchableFeaturedServices {
	title?: string,
	description?: string,
}

export interface C_specialOffers {
	title?: string,
	image?: Image,
	description?: string,
	cTA?: CTA,
}

export interface ProductLists {
	label?: string,
	ids?: string[],
}

export default interface CategoryPage {
	description?: string,
	name: string,
	c_activeOnPages?: boolean,
	c_blueHorizonLocation?: boolean,
	c_categoryPageURL?: string,
	c_centerHomePageURL?: string,
	c_centerNumber?: string,
	c_cityName?: string,
	c_commonName?: string,
	c_corporateMidPageSection?: C_corporateMidPageSection,
	c_corporatePageHeaderSection?: C_corporatePageHeaderSection,
	c_corporateService1ImageAndCopy?: ComplexImage,
	c_corporateService1Link2?: C_corporateService1Link2,
	c_corporateService2ImageAndCopy?: ComplexImage,
	c_corporateService2Link2?: C_corporateService2Link2,
	c_corporateService3ImageAndCopy?: ComplexImage,
	c_corporateService3Link2?: C_corporateService3Link2,
	c_corporateService4ImageAndCopy?: ComplexImage,
	c_corporateService4Link2?: C_corporateService4Link2,
	c_corporateService5ImageAndCopy?: ComplexImage,
	c_corporateService5Link2?: C_corporateService5Link2,
	c_corporateService6ImageAndCopy?: ComplexImage,
	c_corporateService6Link2?: C_corporateService6Link2,
	c_corporateService7ImageAndCopy?: ComplexImage,
	c_corporateService7Link2?: C_corporateService7Link2,
	c_corporateService8ImageAndCopy?: ComplexImage,
	c_corporateService8Link2?: C_corporateService8Link2,
	c_customFAQGroup1?: C_customFAQGroup1,
	c_customFAQGroup2?: C_customFAQGroup2,
	c_customFAQGroup3?: C_customFAQGroup3,
	c_customFeaturedService1ImageAndCopy?: ComplexImage,
	c_customFeaturedService1Link2?: C_customFeaturedService1Link2,
	c_customFeaturedService2ImageAndCopy?: ComplexImage,
	c_customFeaturedService2Link2?: C_customFeaturedService2Link2,
	c_customFeaturedService3ImageAndCopy?: ComplexImage,
	c_customFeaturedService3Link2?: C_customFeaturedService3Link2,
	c_customFeaturedService4ImageAndCopy?: ComplexImage,
	c_customFeaturedService4Link2?: C_customFeaturedService4Link2,
	c_customFeaturedService5ImageAndCopy?: ComplexImage,
	c_customFeaturedService5Link2?: C_customFeaturedService5Link2,
	c_dataFeedStartPrintOrderURL?: string,
	c_defaultFAQGroup1?: C_defaultFAQGroup1,
	c_defaultFAQGroup2?: C_defaultFAQGroup2,
	c_defaultFAQGroup3?: C_defaultFAQGroup3,
	c_displayCorporateFeaturedService1?: boolean,
	c_displayCorporateFeaturedService2?: boolean,
	c_displayCorporateFeaturedService3?: boolean,
	c_displayCorporateFeaturedService4?: boolean,
	c_displayCorporateFeaturedService5?: boolean,
	c_displayCorporateFeaturedService6?: boolean,
	c_displayCorporateFeaturedService7?: boolean,
	c_displayCorporateFeaturedService8?: boolean,
	c_displayDefaultFAQGroup1?: boolean,
	c_displayDefaultFAQGroup2?: boolean,
	c_displayDefaultFAQGroup3?: boolean,
	c_enableCategoryPage?: boolean,
	c_exemptFromETL?: boolean,
	c_featuredServiceTemplateType?: C_featuredServiceTemplateType,
	c_featuredServiceTitle?: string,
	c_featuredVideo?: ComplexVideo[],
	c_featuredVideoDescription?: string,
	c_featuredVideoTitle?: string,
	c_mailboxesCategory?: EntityReference[],
	c_mainLocation?: EntityReference[],
	c_metaDescription?: string,
	c_midPageSection?: C_midPageSection,
	c_moreServicesCategory?: EntityReference[],
	c_ourOffers?: C_ourOffers,
	c_ourServices?: C_ourServices,
	c_pageHeaderSection?: C_pageHeaderSection,
	c_pageTitle?: string,
	c_pricingButton1?: C_pricingButton1,
	c_pricingButton2?: C_pricingButton2,
	c_pricingButton3?: C_pricingButton3,
	c_pricingField1?: C_pricingField1,
	c_pricingField10?: C_pricingField10,
	c_pricingField11?: C_pricingField11,
	c_pricingField12?: C_pricingField12,
	c_pricingField2?: C_pricingField2,
	c_pricingField3?: C_pricingField3,
	c_pricingField4?: C_pricingField4,
	c_pricingField5?: C_pricingField5,
	c_pricingField6?: C_pricingField6,
	c_pricingField7?: C_pricingField7,
	c_pricingField8?: C_pricingField8,
	c_pricingField9?: C_pricingField9,
	c_printCategory?: EntityReference[],
	c_reactSpanishCategoryContent?: EntityReference[],
	c_reactStagingEnabled?: boolean,
	c_searchableFeaturedServices?: C_searchableFeaturedServices[],
	c_shipAndPackCategory?: EntityReference[],
	c_slug?: string,
	c_slugAddress?: string,
	c_slugName?: string,
	c_slugSpanishName?: string,
	c_spanishCategoryContent?: EntityReference[],
	c_specialOffers?: C_specialOffers[],
	c_stateName?: string,
	c_storeAddress?: string,
	c_storeEmail?: string,
	c_storePhone?: string,
	c_storeZipCode?: string,
	c_yextScheduleAppointmentURL?: string,
	productLists?: ProductLists,
	id: string,
}
