export interface Interval {
	start: any,
	end: any,
}

export interface DayHour {
	openIntervals?: Interval[],
	isClosed?: boolean,
}

export interface HolidayHours {
	date: string,
	openIntervals?: Interval[],
	isClosed?: boolean,
	isRegularHours?: boolean,
}

export interface Hours {
	monday?: DayHour,
	tuesday?: DayHour,
	wednesday?: DayHour,
	thursday?: DayHour,
	friday?: DayHour,
	saturday?: DayHour,
	sunday?: DayHour,
	holidayHours?: HolidayHours[],
	reopenDate?: string,
}

export enum Category {
	BOOK_TRAVEL = "Book Travel",
	CHECK_IN = "Check in",
	FEES_POLICIES = "Fees Policies - Deprecated",
	FLIGHT_STATUS = "Flight Status",
	TICKETS = "Tickets",
	TICKETING = "Ticketing - Deprecated",
	AMENITIES = "Amenities",
	RESERVE_DEP = "Reserve - Deprecated",
	FRONT_DESK = "Front Desk - Deprecated",
	PARKING = "Parking",
	GIFT_CARD = "Gift Card",
	WAITLIST = "Waitlist",
	DELIVERY = "Delivery (Restaurant)",
	ORDER = "Order (Restaurant)",
	TAKEOUT = "Takeout - Deprecated",
	PICKUP = "Pickup (Restaurant)",
	RESERVE = "Reserve (Restaurant)",
	MENU = "Menu",
	APPOINTMENT = "Appointment - Deprecated",
	PORTFOLIO = "Portfolio - Deprecated",
	QUOTE = "Quote",
	SERVICES = "Services",
	STORE_ORDERS = "Store Orders - Deprecated",
	STORE_SHOP = "Store Shop - Deprecated",
	STORE_SUPPORT = "Store Support - Deprecated",
	SCHEDULE = "Schedule",
	SHOWTIMES = "Showtimes",
	AVAILABILITY = "Availability",
	PRICING = "Pricing",
	ACTIVITIES = "Activities",
	BOOK = "Book",
	BOOK__HOTEL_ = "Book (Hotel)",
	BOOK__RIDE_ = "Book Ride",
	BOOK__TOUR_ = "Book Tour",
	CAREERS = "Careers",
	CHARGE = "Charge",
	COUPONS = "Coupons",
	DELIVERY__RETAIL_ = "Delivery (Retail)",
	DONATE = "Donate",
	EVENTS = "Events",
	ORDER__RETAIL_ = "Order (Retail)",
	OTHER_MENU = "Other Menu - Deprecated",
	PICKUP__RETAIL_ = "Pickup (Retail)",
	RESERVE__PARKING_ = "Reserve (Parking)",
	SHOWS = "Shows",
	SPORTS = "Sports",
	SUPPORT = "Support",
	TEE_TIME = "Tee Time",
	GIFT_CARD__RESTAURANT_ = "Gift Card (Restaurant) - Deprecated",
}

export interface AppleActionLinks {
	category: Category,
	appStoreUrl: string,
	quickLinkUrl: string,
	appName: string,
}

export interface ImageThumbnail {
	url: string,
	width: number,
	height: number,
}

export interface Image {
	url: string,
	width: number,
	height: number,
	thumbnails?: ImageThumbnail[],
	alternateText?: string,
}

export interface FrequentlyAskedQuestions {
	question: string,
	answer?: string,
}

export enum Type {
	DEPARTMENT_IN = "Department In",
	INDEPENDENT_ESTABLISHMENT_IN = "Independent Establishment In",
}

export interface GoogleEntityRelationship {
	type: Type,
	placeId: string,
}

export enum PickupAndDeliveryServices {
	IN_STORE_PICKUP = "In-Store Pickup",
	CURBSIDE_PICKUP = "Curbside Pickup",
	PICKUP_NOT_OFFERED = "Pickup Not Offered",
	DELIVERY = "Delivery",
	SAME_DAY_DELIVERY = "Same Day Delivery",
	NO_CONTACT_DELIVERY = "No-Contact Delivery",
	DELIVERY_NOT_OFFERED = "Delivery Not Offered",
}

export enum Type_1 {
	POSTAL_CODE = "Postal Code",
	REGION = "State/Region",
	COUNTY = "County",
	CITY = "City",
	SUBLOCALITY = "Sublocality",
}

export interface ServiceAreaPlaces {
	name?: string,
	type?: Type_1,
}

export interface Address {
	line1?: string,
	line2?: string,
	line3?: string,
	sublocality?: string,
	city?: string,
	region?: string,
	postalCode?: string,
	extraDescription?: string,
	countryCode?: string,
}

export interface ComplexImage {
	image: Image,
	details?: string,
	description?: string,
	clickthroughUrl?: string,
}

export interface Coordinate {
	latitude?: number,
	longitude?: number,
}

export interface EntityReference {
	entityId: string,
	name: string,
}

export enum C_bLocalOffer1Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	START_PRINT_ORDER = "Start Print Order",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_bLocalStorePromo1Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_cTitle {
	FRANCHISE_OWNER = "Franchise Owner",
	STORE_MANAGER = "Store Manager",
	ASSOCIATE = "Associate",
}

export enum C_dLocalStorePromo2Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_fLocalStorePromo3Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	AUCTION_SHIPPING_QUOTE = "Auction Shipping Quote",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_gLocalOffer2Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	START_PRINT_ORDER = "Start Print Order",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_iBorderColor {
	YELLOW = "Yellow",
	BLUE = "Blue",
	GREEN = "Green",
}

export enum C_lLocalOffer3Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	START_PRINT_ORDER = "Start Print Order",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_activeInAnswers {
	YES = "Yes",
	NO = "No",
}

export enum C_dataFeedStoreStatus {
	OPEN = "Open",
	WAITING_TO_OPEN = "Waiting To Open",
	CLOSED = "Closed",
}

export interface HolidayTime {
	date: string,
	time?: any,
}

export interface C_dataFeedUPSAirPickupTimes {
	monday?: any,
	tuesday?: any,
	wednesday?: any,
	thursday?: any,
	friday?: any,
	saturday?: any,
	sunday?: any,
	holidayTimes?: HolidayTime[],
}

export interface C_dataFeedUPSGroundPickupTimes {
	monday?: any,
	tuesday?: any,
	wednesday?: any,
	thursday?: any,
	friday?: any,
	saturday?: any,
	sunday?: any,
	holidayTimes?: HolidayTime[],
}

export interface C_franchiseeStorySectionNew {
	title?: string,
	description?: string,
	photo?: Image,
	src?: string,
	datauuid?: string,
}

export interface LeftSideText {
	aboveBox?: string,
	insideBox?: string,
	belowBox?: string,
}

export interface C_holidayBanner {
	leftSideText?: LeftSideText,
	rightSideText?: string,
}

export interface C_holidayHoursSearch {
	date?: string,
	holiday?: string,
}

export interface C_nonTraditionalStoreContent {
	nonTraditionalLocation?: boolean,
	nonTraditionalLocationHeroImage?: Image,
	nonTraditionalCategoryHeroImage?: Image,
	nonTraditionalLogo?: Image,
	nonTraditionalInteriorImage?: Image,
	nonTraditionalAccessRestrictedMessage?: string,
	nonTraditionalAdditionalLocationInformation?: string,
}

export enum C_pagesGMBAttributes {
	BLACK_OWNED = "Black-Owned",
	WOMEN_LED = "Women-Led",
	VETERAN_LED = "Veteran-Led",
}

export interface C_productsAndServices {
	title?: string,
	productServices?: string[],
}

export interface C_promoCarouselBlueHorizon {
	title?: string,
	description?: string,
}

export enum C_promoCarouselCorporate1Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_promoCarouselCorporate2Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_promoCarouselCorporate3Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_promoCarouselDMA1Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ADDITIONAL_SERVICES = "Additional Services",
	ALL_PRINTING_SERVICES = "All Printing Services",
	ALL_SHIPPING___PACKAGING_SERVICES = "All Shipping & Packaging Services",
	BANNERS__POSTERS___SIGNS = "Banners, Posters & Signs",
	COPIES___DOCUMENTS = "Copies & Documents",
	FREIGHT_SHIPPING = "Freight Shipping",
	HOUSE_ACCOUNTS = "House Accounts",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MAILBOX_SERVICES = "Mailbox Services",
	MARKETING_MATERIALS = "Marketing Materials",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	NOTARY_SERVICES = "Notary Services",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	PASSPORT_PHOTOS = "Passport Photos",
	REGISTER_NOW = "Register Now",
	SHREDDING_SERVICES = "Shredding Services",
	STATIONERY___CARDS = "Stationery & Cards",
	STUDENT_STORAGE = "Student Storage",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export interface C_shippingServicesService1 {
	image?: Image,
	title?: string,
	description?: string,
	clickThroughURL?: string,
}

export enum C_shippingServicesService1Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	FREIGHT_SHIPPING = "Freight Shipping",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export interface C_shippingServicesService2 {
	image?: Image,
	title?: string,
	description?: string,
	clickThroughURL?: string,
}

export enum C_shippingServicesService2Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	FREIGHT_SHIPPING = "Freight Shipping",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export interface C_shippingServicesService3 {
	image?: Image,
	title?: string,
	description?: string,
	clickThroughURL?: string,
}

export enum C_shippingServicesService3Button {
	GET_STARTED = "Get Started",
	LEARN_MORE = "Learn More",
	SCHEDULE_APPOINTMENT = "Schedule Appointment",
	START_PRINT_ORDER = "Start Print Order",
	CONTACT_US = "Contact Us",
	ALL_SHIPPING___PACKING_SERVICES = "All Shipping & Packing Services",
	FREIGHT_SHIPPING = "Freight Shipping",
	INTERNATIONAL_SHIPPING = "International Shipping",
	MOVING_BOXES___SUPPLIES = "Moving Boxes & Supplies",
	PACKING___SHIPPING_BOXES = "Packing & Shipping Boxes",
	UPS_SHIPPING = "UPS Shipping",
	ESTIMATE_SHIPPING_COST = "Estimate Shipping Cost",
}

export enum C_storeFeatures {
	WHEELCHAIR_ACCESSIBLE_ENTRANCE = "Wheelchair accessible entrance",
	WHEELCHAIR_ACCESSIBLE_RESTROOM = "Wheelchair accessible restroom",
	WHEELCHAIR_ACCESSIBLE_SEATING = "Wheelchair accessible seating",
	GENDER_NEUTRAL_RESTROOM = "Gender-neutral restroom",
	WI_FI = "Wi-Fi",
	LGBTQ__FRIENDLY = "LGBTQ+ friendly",
	TRANSGENDER_SAFESPACE = "Transgender safespace",
	PLASTIC_FOAM = "Plastic foam",
	CURBSIDE_PICKUP = "Curbside pickup",
	DELIVERY = "Delivery",
	IN_STORE_PICKUP = "In-store pickup",
	IN_STORE_SHOPPING = "In-store shopping",
}

export interface ProductLists {
	label?: string,
	ids?: string[],
}

export enum Type_2 {
	NONE = "None",
	BOOK_NOW = "Book Now",
	CALL_NOW = "Call Now",
	CONTACT_US = "Contact Us",
	SEND_MESSAGE = "Send Message",
	USE_APP = "Use App",
	PLAY_GAME = "Play Game",
	SHOP_NOW = "Shop Now",
	SIGN_UP = "Sign Up",
	WATCH_VIDEO = "Watch Video",
	SEND_EMAIL = "Send Email",
	LEARN_MORE = "Learn More",
	PURCHASE_GIFT_CARDS = "Purchase Gift Cards",
	ORDER_NOW = "Order Now",
	FOLLOW_PAGE = "Follow Page",
}

export interface FacebookCallToAction {
	type: Type_2,
	value?: string,
}

export interface FeaturedMessage {
	description?: string,
	url?: string,
}

export enum LocationType {
	LOCATION = "Location",
	HEALTHCARE_FACILITY = "Healthcare Facility",
	HEALTHCARE_PROFESSIONAL = "Healthcare Professional",
	ATM = "ATM",
	RESTAURANT = "Restaurant",
	HOTEL = "Hotel",
}

export interface MenuUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface OrderUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export enum PaymentOptions {
	AFTERPAY = "Afterpay",
	ALIPAY = "Alipay",
	AMERICANEXPRESS = "American Express",
	ANDROIDPAY = "Google Pay",
	APPLEPAY = "Apple Pay",
	ATM = "ATM",
	ATMQUICK = "ATM Quick",
	BACS = "BACS",
	BANCONTACT = "Bancontact",
	BANKDEPOSIT = "Bank Deposit",
	BANKPAY = "Bank Pay",
	BGO = "Bank/Giro Overschrijving",
	BITCOIN = "Bitcoin",
	Bar = "Bargeld",
	CARTASI = "CartaSi",
	CASH = "Cash",
	CCS = "CCS",
	CHECK = "Check",
	CONB = "Contactloos betalen",
	CONTACTLESSPAYME = "Contactless Payment",
	CVVV = "Cadeaubon/VVV bon",
	DEBITNOTE = "Debit Note",
	DINERSCLUB = "Diners Club",
	DIRECTDEBIT = "Direct Debit",
	DISCOVER = "Discover",
	ECKARTE = "Girokarte",
	ECOCHEQUE = "EcoCheque",
	EKENA = "E-kena",
	EMV = "Elektronische Maaltijdcheques",
	FINANCING = "Financing",
	GOPAY = "GoPay",
	HAYAKAKEN = "Hayakaken",
	HEBAG = "He-Bag",
	IBOD = "iBOD",
	ICCARDS = "IC Cards",
	ICOCA = "Icoca",
	ID = "iD",
	IDEAL = "iDeal",
	INCA = "Incasso",
	INVOICE = "Invoice",
	JCB = "JCB",
	JCoinPay = "J−Coin Pay",
	JKOPAY = "JKO Pay",
	KITACA = "Kitaca",
	KLA = "Klantenkaart",
	KLARNA = "Klarna",
	LINEPAY = "LINE Pay",
	MAESTRO = "Maestro",
	MANACA = "Manaca",
	MASTERCARD = "MasterCard",
	MIPAY = "Mi Pay",
	MONIZZE = "Monizze",
	MPAY = "MPay",
	Manuelle_Lastsch = "Manuelle Lastschrift",
	Merpay = "メルPay",
	NANACO = "nanaco",
	NEXI = "Nexi",
	NIMOCA = "Nimoca",
	OREM = "Onder Rembours",
	PASMO = "Pasmo",
	PAYBACKPAY = "Payback Pay",
	PAYBOX = "Paybox",
	PAYCONIQ = "Payconiq",
	PAYPAL = "PayPal",
	PAYPAY = "PayPay",
	PAYSEC = "PaySec",
	PIN = "PIN",
	POSTEPAY = "Postepay",
	QRCODE = "QR Code Payment",
	QUICPAY = "QUICPay",
	RAKUTENEDY = "Rakuten Edy",
	RAKUTENPAY = "楽天Pay",
	SAMSUNGPAY = "Samsung Pay",
	SODEXO = "Sodexo",
	SUGOCA = "Sugoca",
	SUICA = "Suica",
	SWISH = "Swish",
	TICKETRESTAURANT = "Ticket Restaurant",
	TOICA = "Toica",
	TRAVELERSCHECK = "Traveler's Check",
	TSCUBIC = "TS CUBIC",
	TWINT = "Twint",
	UNIONPAY = "China UnionPay",
	VEV = "Via een verzekering",
	VISA = "Visa",
	VISAELECTRON = "Visa Electron",
	VOB = "Vooruit betalen",
	VOUCHER = "Voucher",
	VPAY = "V PAY",
	WAON = "WAON",
	WECHATPAY = "WeChat Pay",
	WIRETRANSFER = "Wire Transfer",
	Yucho_Pay = "ゆうちょPay",
	ZELLE = "Zelle",
	AuPay = "auPay",
	DBarai = "d払い ",
	Überweisung = "Banküberweisung",
}

export enum PriceRange {
	UNSPECIFIED = "Unspecified",
	ONE = "$",
	TWO = "$$",
	THREE = "$$$",
	FOUR = "$$$$",
}

export interface RankTrackingCompetitors {
	name: string,
	website: string,
}

export enum RankTrackingFrequency {
	WEEKLY = "Weekly",
	MONTHLY = "Monthly",
	QUARTERLY = "Quarterly",
}

export enum RankTrackingKeywords {
	NAME = "Name",
	PRIMARY_CATEGORY = "Primary Category",
	SECONDARY_CATEGORY = "Secondary Category",
}

export enum RankTrackingQueryTemplates {
	KEYWORD = "Keyword",
	KEYWORD_ZIP = "Keyword Zip",
	KEYWORD_CITY = "Keyword City",
	KEYWORD_IN_CITY = "Keyword in City",
	KEYWORD_NEAR_ME = "Keyword near me",
	KEYWORD_CITY_STATE = "Keyword City State",
}

export enum RankTrackingSites {
	GOOGLE_DESKTOP = "Google Desktop",
	GOOGLE_MOBILE = "Google Mobile",
	BING_DESKTOP = "Bing Desktop",
	BING_MOBILE = "Bing Mobile",
	YAHOO_DESKTOP = "Yahoo Desktop",
	YAHOO_MOBILE = "Yahoo Mobile",
}

export interface ReservationUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface ServiceArea {
	places?: string[],
}

export enum Presentation {
	BUTTON = "Button",
	LINK = "Link",
}

export interface UberLink {
	text?: string,
	presentation: Presentation,
}

export interface UberTripBranding {
	text: string,
	url: string,
	description: string,
}

export interface WebsiteUrl {
	url?: string,
	displayUrl?: string,
	preferDisplayUrl?: boolean,
}

export interface ComplexVideo {
	url: string,
	video?: string,
	description?: string,
}

export default interface Location {
	accessHours?: Hours,
	appleActionLinks?: AppleActionLinks[],
	appleBusinessConnectLinkedAccount?: any,
	appleBusinessDescription?: string,
	appleBusinessId?: string,
	appleBusinessIdDqe?: string,
	appleCompanyId?: string,
	appleCompanyIdDqe?: string,
	appleCoverPhoto?: Image,
	bingWebsiteOverride?: string,
	blackOwnedBusiness?: boolean,
	bookingDotComPropertyId?: string,
	brunchHours?: Hours,
	questionsAndAnswers?: boolean,
	covid19InformationUrl?: string,
	covidMessaging?: string,
	deliveryHours?: Hours,
	deliveryUrl?: string,
	dineInHours?: Hours,
	driveThroughHours?: Hours,
	facebookAbout?: string,
	facebookWebsiteOverride?: string,
	frequentlyAskedQuestions?: FrequentlyAskedQuestions[],
	fullyVaccinatedStaff?: boolean,
	geomodifier?: string,
	googleEntityRelationship?: GoogleEntityRelationship,
	googleMyBusinessLabels?: string[],
	googlePlaceId?: string,
	googleShortName?: string,
	happyHours?: Hours,
	holidayHoursConversationEnabled?: boolean,
	impressum?: string,
	kitchenHours?: Hours,
	landingPageUrl?: string,
	linkedInUrl?: string,
	neighborhood?: string,
	nudgeEnabled?: boolean,
	onlineServiceHours?: Hours,
	phoneticName?: string,
	pickupAndDeliveryServices?: PickupAndDeliveryServices[],
	pickupHours?: Hours,
	pinterestUrl?: string,
	primaryConversationContact?: any,
	proofOfVaccinationRequired?: boolean,
	reviewResponseConversationEnabled?: boolean,
	seniorHours?: Hours,
	serviceAreaPlaces?: ServiceAreaPlaces[],
	slug?: string,
	takeoutHours?: Hours,
	tikTokUrl?: string,
	what3WordsAddress?: string,
	yelpKnowledgeLinkedAccount?: any,
	yelpLinkedAccount?: any,
	yelpWebsiteOverride?: string,
	youTubeChannelUrl?: string,
	additionalHoursText?: string,
	address: Address,
	addressHidden?: boolean,
	alternatePhone?: any,
	androidAppUrl?: string,
	associations?: string[],
	brands?: string[],
	description?: string,
	hours?: Hours,
	logo?: ComplexImage,
	name: string,
	categories?: any,
	cityCoordinate?: Coordinate,
	closed?: boolean,
	c_aDisplayAdditionalServices?: boolean,
	c_aDisplayNearbyLocations?: boolean,
	c_aDisplayUberButtonOnMobile?: boolean,
	c_aFranchiseeOrStaffPhoto?: ComplexImage,
	c_aLocalOffer1ImageAndCopy?: ComplexImage,
	c_aLocalStorePromo1ImageAndCopy?: ComplexImage,
	c_aStoreFrontPhoto?: ComplexImage,
	c_bAdditionalServicesImageAndCopy?: ComplexImage,
	c_bCustomizeNearbyLocations?: EntityReference[],
	c_bDisplayFirstPartyReviews?: boolean,
	c_bFranchiseeOrStaffNames?: string,
	c_bLocalNameShoppingCenterOrNeighborhood?: string,
	c_bLocalOffer1Button?: C_bLocalOffer1Button,
	c_bLocalStorePromo1Button?: C_bLocalStorePromo1Button,
	c_cDisplayHouseAccounts?: boolean,
	c_cHomePageLocalAlertMessage?: string,
	c_cLocalOffer1CouponPriceOrDiscount?: string,
	c_cLocalStorePromo2ImageAndCopy?: ComplexImage,
	c_cNearbyLocationsSectionTitle?: string,
	c_cTitle?: C_cTitle,
	c_cWelcomeMessage?: string,
	c_dAboutUsDescription?: string,
	c_dConstantContactLandingPageURL?: string,
	c_dDisplayFacebookIcon?: boolean,
	c_dHouseAccountsImageAndCopy?: ComplexImage,
	c_dLocalOffer1CouponProductOrService?: string,
	c_dLocalStorePromo2Button?: C_dLocalStorePromo2Button,
	c_dLocationDirectionsOrCrossStreets?: string,
	c_eAreasServed?: string,
	c_eCustomizeJoinMailingListCopy?: string,
	c_eDisplayGoogleIcon?: boolean,
	c_eDisplayStudentStorage?: boolean,
	c_eLocalOffer1CouponExpirationDate?: string,
	c_eLocalStorePromo3ImageAndCopy?: ComplexImage,
	c_eStoreHoursMessage?: string,
	c_fDisplayInstagramIcon?: boolean,
	c_fGoogleTagManagerID?: string,
	c_fLocalOffer2ImageAndCopy?: ComplexImage,
	c_fLocalStorePromo3Button?: C_fLocalStorePromo3Button,
	c_fStoreParking?: string,
	c_fStudentStorageImageAndCopy?: ComplexImage,
	c_fUPSAirPickupTimesMessage?: string,
	c_gDisplayCorporatePromo1?: boolean,
	c_gDisplayLinkedInIcon?: boolean,
	c_gDisplayMailboxes?: boolean,
	c_gGoogleAnalyticsID?: string,
	c_gLocalOffer2Button?: C_gLocalOffer2Button,
	c_gStoreServicesDescription?: string,
	c_gUPSGroundPickupTimesMessage?: string,
	c_hDisplayCorporatePromo2?: boolean,
	c_hDisplayNotary?: boolean,
	c_hDisplayTwitterIcon?: boolean,
	c_hLocalOffer2CouponPriceOrDiscount?: string,
	c_hOtherAnalyticsScript?: string,
	c_hSeniorHours?: Hours,
	c_iAdvertisingPixel1?: string,
	c_iBorderColor?: C_iBorderColor,
	c_iDisplayCorporatePromo3?: boolean,
	c_iDisplayPassportPhotos?: boolean,
	c_iDisplayYelpIcon?: boolean,
	c_iLocalOffer2CouponProductOrService?: string,
	c_jAdvertisingPixel2?: string,
	c_jDisplayShredding?: boolean,
	c_jDisplayYouTubeIcon?: boolean,
	c_jLocalOffer2CouponExpirationDate?: string,
	c_kDisplayAllPrintingServices?: boolean,
	c_kDisplayCorporateAboutUsDescription?: boolean,
	c_kLocalOffer3ImageAndCopy?: ComplexImage,
	c_kPageTitle?: string,
	c_lDisplayBannersPostersAndSigns?: boolean,
	c_lLocalOffer3Button?: C_lLocalOffer3Button,
	c_lMetaDescription?: string,
	c_mDisplayCopiesAndDocuments?: boolean,
	c_mLinkedInURL?: string,
	c_mLocalOffer3CouponPriceOrDiscount?: string,
	c_nDisplayMarketingMaterials?: boolean,
	c_nGoogleMyBusinessURL?: string,
	c_nLocalOffer3CouponProductOrService?: string,
	c_oDisplayStartPrintOrderLink?: boolean,
	c_oLocalOffer3CouponExpirationDate?: string,
	c_oYelpURL?: string,
	c_pDisplayStationeryAndCards?: boolean,
	c_pFacebookURL?: string,
	c_qDisplayAllShippingAndPacking?: boolean,
	c_rDisplayFreightShipping?: boolean,
	c_sDisplayInternationalShipping?: boolean,
	c_tDisplayMovingBoxesAndSupplies?: boolean,
	c_uDisplayPackingAndShippingBoxes?: boolean,
	c_vDisplayUPSShippingServices?: boolean,
	c_wDisplayCustomServicePage?: boolean,
	c_wDisplayEstimateShippingCostPage?: boolean,
	c_xCustomServiceDisplayName?: string,
	c_xEnableEstimateShippingCostEmailToStore?: boolean,
	c_yCustomServicePageImageAndCopy?: ComplexImage,
	c_yRequestCustomServicePage?: boolean,
	c_zCustomServicePageLinkCopy?: string,
	c_zDisplayBrochures?: boolean,
	c_zADisplayPostcards?: boolean,
	c_zBDisplayBusinessCards?: boolean,
	c_zCDisplayDirectMail?: boolean,
	c_zDDisplayBlueprintsArchitecturalPrinting?: boolean,
	c_zEDisplayLockers?: boolean,
	c_zFDisplayPackAndShipGuarantee?: boolean,
	c_zGLockersImageAndCopy?: ComplexImage,
	c_zHDisplayFaxingAndScanning?: boolean,
	c_zNDisplayScheduleAppointment?: boolean,
	c_zIFaxingAndScanningImageAndCopy?: ComplexImage,
	c_zJDisplayBannerPrinting?: boolean,
	c_zKDisplayPosterPrinting?: boolean,
	c_zLDisplaySignPrinting?: boolean,
	c_zMDisplayPostalServices?: boolean,
	c_zODisplayTimeSavingKiosk?: boolean,
	c_zPTimeSavingKioskImageAndCopy?: ComplexImage,
	c_aboutCorporateDefaultText?: string,
	c_aboutLocalOwnedText?: string,
	c_aboutStaffDefaultImage?: ComplexImage,
	c_aboutStoreServicesCorporateDefaultText?: string,
	c_activeInAnswers?: C_activeInAnswers,
	c_activeOnPages?: boolean,
	c_alertBannerCorporate?: string,
	c_answersSearchPageURL?: string,
	c_associatedCoOp?: EntityReference[],
	c_blueHorizonLocation?: boolean,
	c_dashboardCompletionPercentage?: string,
	c_dataFeedArea?: string,
	c_dataFeedCenterLocation?: string,
	c_dataFeedClosedStoreDate?: string,
	c_dataFeedCommonName?: string,
	c_dataFeedDMA?: string,
	c_dataFeedEntityName?: string,
	c_dataFeedRegion?: string,
	c_dataFeedStartPrintOrderURL?: string,
	c_dataFeedStoreID?: string,
	c_dataFeedStoreStatus?: C_dataFeedStoreStatus,
	c_dataFeedStreetName?: string,
	c_dataFeedUPSAirPickupTimes?: C_dataFeedUPSAirPickupTimes,
	c_dataFeedUPSGroundPickupTimes?: C_dataFeedUPSGroundPickupTimes,
	c_daysOpenOnWeekend?: string[],
	dm_directoryParents?: EntityReference[],
	c_displaySpanishPages?: boolean,
	c_exemptFromETL?: boolean,
	c_franchiseeStory?: EntityReference[],
	c_franchiseeStorySectionNew?: C_franchiseeStorySectionNew,
	c_googleReviewLink?: string,
	c_holidayBanner?: C_holidayBanner,
	c_holidayCountdownTimer?: boolean,
	c_holidayHoursSearch?: C_holidayHoursSearch[],
	c_localOffersCouponDisclaimer?: string,
	c_locationAlertBlock?: string,
	c_mailboxes?: string[],
	c_mailboxesCategory?: EntityReference[],
	c_mainServicesSectionMailboxCopy?: string,
	c_mainServicesSectionPrintingCopy?: string,
	c_mainServicesSectionShippingCopy?: string,
	c_moreServices?: string[],
	c_moreServicesCategory?: EntityReference[],
	c_nonTraditionalStoreContent?: C_nonTraditionalStoreContent,
	c_pagesGMBAttributes?: C_pagesGMBAttributes[],
	c_print?: string[],
	c_printCategory?: EntityReference[],
	c_productsAndServices?: C_productsAndServices[],
	c_promoCarouselBlueHorizon?: C_promoCarouselBlueHorizon,
	c_promoCarouselCorporate1?: ComplexImage,
	c_promoCarouselCorporate1Button?: C_promoCarouselCorporate1Button,
	c_promoCarouselCorporate2?: ComplexImage,
	c_promoCarouselCorporate2Button?: C_promoCarouselCorporate2Button,
	c_promoCarouselCorporate3?: ComplexImage,
	c_promoCarouselCorporate3Button?: C_promoCarouselCorporate3Button,
	c_promoCarouselDMA1?: ComplexImage,
	c_promoCarouselDMA1Button?: C_promoCarouselDMA1Button,
	c_reactSpanishLocationContent?: EntityReference[],
	c_searchMetaDescription?: string,
	c_searchMetaTitle?: string,
	c_searchPromoBanner?: EntityReference[],
	c_servicesSectionAdditionalLink?: string,
	c_servicesSectionFaxingAndScanningLink?: string,
	c_servicesSectionHouseAccountLink?: string,
	c_servicesSectionLockersLink?: string,
	c_servicesSectionNotaryImageAndCopy?: ComplexImage,
	c_servicesSectionNotaryLink?: string,
	c_servicesSectionPassportImageAndCopy?: ComplexImage,
	c_servicesSectionPassportLink?: string,
	c_servicesSectionShreddingImageAndCopy?: ComplexImage,
	c_servicesSectionShreddingLink?: string,
	c_servicesSectionStudentStorageLink?: string,
	c_servicesSectionTimeSavingKioskLink?: string,
	c_shipAndPack?: string[],
	c_shipAndPackCategory?: EntityReference[],
	c_shippingServicesService1?: C_shippingServicesService1,
	c_shippingServicesService1Button?: C_shippingServicesService1Button,
	c_shippingServicesService2?: C_shippingServicesService2,
	c_shippingServicesService2Button?: C_shippingServicesService2Button,
	c_shippingServicesService3?: C_shippingServicesService3,
	c_shippingServicesService3Button?: C_shippingServicesService3Button,
	c_showReviewsSection?: boolean,
	c_slug?: string,
	c_spanishLocationContent?: EntityReference[],
	c_storeFeatures?: C_storeFeatures[],
	c_storeWebsiteURL?: string,
	c_yextExcludedFromYext?: boolean,
	c_yextScheduleAppointmentURL?: string,
	c_yextWebsiteTracking?: string,
	displayCoordinate?: Coordinate,
	dropoffCoordinate?: Coordinate,
	productLists?: ProductLists,
	emails?: string[],
	facebookOverrideCity?: string,
	facebookCoverPhoto?: Image,
	facebookCallToAction?: FacebookCallToAction,
	facebookDescriptor?: string,
	facebookEmail?: string,
	facebookLinkedAccount?: any,
	facebookName?: string,
	facebookPageUrl?: string,
	facebookParentPageId?: string,
	facebookProfilePhoto?: Image,
	facebookStoreId?: string,
	facebookVanityUrl?: string,
	fax?: any,
	featuredMessage?: FeaturedMessage,
	photoGallery?: ComplexImage[],
	geocodedCoordinate?: Coordinate,
	gmbLinkedAccount?: any,
	googleAccountId?: string,
	googleAttributes?: any,
	googleCoverPhoto?: Image,
	googleProfilePhoto?: Image,
	googleWebsiteOverride?: string,
	instagramHandle?: string,
	iosAppUrl?: string,
	isoRegionCode?: string,
	keywords?: string[],
	languages?: string[],
	localPhone?: any,
	locationType?: LocationType,
	mainPhone?: any,
	menuUrl?: MenuUrl,
	mobilePhone?: any,
	orderUrl?: OrderUrl,
	paymentOptions?: PaymentOptions[],
	phones?: any,
	pickupCoordinate?: Coordinate,
	priceRange?: PriceRange,
	products?: string[],
	alternateNames?: string[],
	alternateWebsites?: string[],
	rankTrackingCompetitors?: RankTrackingCompetitors[],
	customKeywords?: string[],
	rankTrackingEnabled?: boolean,
	rankTrackingFrequency?: RankTrackingFrequency,
	rankTrackingKeywords?: RankTrackingKeywords[],
	rankTrackingQueryTemplates?: RankTrackingQueryTemplates[],
	rankTrackingSites?: RankTrackingSites[],
	reservationUrl?: ReservationUrl,
	routableCoordinate?: Coordinate,
	serviceArea?: ServiceArea,
	services?: string[],
	shortName35?: string,
	shortName64?: string,
	specialities?: string[],
	id: string,
	timezone?: any,
	tollFreePhone?: any,
	ttyPhone?: any,
	twitterHandle?: string,
	uberClientId?: string,
	uberLink?: UberLink,
	uberTripBranding?: UberTripBranding,
	walkableCoordinate?: Coordinate,
	websiteUrl?: WebsiteUrl,
	yearEstablished?: number,
	yextDisplayCoordinate?: Coordinate,
	yextDropoffCoordinate?: Coordinate,
	yextPickupCoordinate?: Coordinate,
	yextRoutableCoordinate?: Coordinate,
	yextWalkableCoordinate?: Coordinate,
	videos?: ComplexVideo[],
}
